### PR TITLE
Python port!

### PR DESCRIPTION
**Pull request by luqmana**
Converted the original PHP script to a Python script. You can use both together. Also includes support for the ini files.

### CODE REVIEW

**Comment by viccherubini** [comment]
You are badass! That's awesome, I appreciate it.

**Comment by luqmana** [comment]
lol badass? Hardly. Still new with python so I was googling a lot xD

**Comment by viccherubini** [comment]
Well just the idea you took the time to do it was badass. I really appreciate it. I'm a python newbie too, so it gives me something good to start with.

**Comment by dananjayavr** [comment]
There's another Python port :-) https://github.com/dananjayavr/get-shit-done

**Pull request merged**
